on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Render and Publish
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto
        shell: bash -l {0}
        run: |
          quarto render src/analysisShell.qmd

      - name: Copy Quarto html
        shell: bash -l {0}
        run: |
          cp ./src/analysisShell.html ./web  

      - name: Publish
        uses: actions/upload-pages-artifact@v1
        with:
          path: web/

      - name: Create report file
        run: date +%s > report.txt 
                 
      - name: Commit report
        uses: maxgfr/github-commit-push-file@main
        with: 
          commit_name: 'fix'    

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 # or specific "vX.X.X" version tag for this action

  # Commit:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Create report file
  #       run: date +%s > report.txt
  #     - name: Commit report
  #       uses: maxgfr/github-commit-push-file@main
  #       with: 
  #         commit_name: 'fix'